CREATE TABLE `user` (
  `ID` varchar(100) NOT NULL,
  `PASSWORD` varchar(300) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `AUTHORITY` varchar(50) NOT NULL DEFAULT 'ROLE_USER',
  `ENABLED` tinyint(1) unsigned zerofill DEFAULT '1',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE BOARD (
	board_id BIGINT(20) NOT NULL AUTO_INCREMENT,
	name VARCHAR(255),
	create_at TIMESTAMP,
	modified_at TIMESTAMP,
	PRIMARY KEY(board_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE POST (
	post_id BIGINT(20) NOT NULL AUTO_INCREMENT,
	board_id BIGINT(20) NOT NULL,
	UID VARCHAR(100) NOT NULL,
	title VARCHAR(255),
	author VARCHAR(255),
	content VARCHAR(255),
	create_at TIMESTAMP,
	modified_at TIMESTAMP,
	PRIMARY KEY(post_id),
	FOREIGN KEY(board_id)
	REFERENCES BOARD(board_id),
	FOREIGN KEY(UID)
	REFERENCES USER(UID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

